name: uc-python
channels:
    - defaults
    - conda-forge
dependencies:
    - category_encoders>=2.2
    - ipykernel>=6.4
    - matplotlib>=3.5
    - missingno>=0.4
    - mlflow=1.22
    - nbconvert>=6.1
    - numpy>=1.21
    - pandas>=1.3
    - pip>=21.2
    - plotnine>=0.8
    - pytest>=6.2
    - python=3.9
    - scikit-learn>=1.0
    - seaborn>=0.11
